# .github/workflows/mirror.yml
name: Mirror main branch to personal repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # fetch full history

      - name: Push main branch to personal repo
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          echo "🔍 Testing connection to personal repo..."
          git ls-remote https://mifraheem:${PAT}@github.com/mifraheem/nuxused-frontend-mirror.git

          echo "🚀 Pushing main branch..."
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git push https://mifraheem:${PAT}@github.com/mifraheem/nuxused-frontend-mirror.git main --force