name: Mirror to personal repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Push to personal repo
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git remote add personal https://mifraheem:${{ secrets.PERSONAL_TOKEN }}@github.com/mifraheem/nuxused-frontend-mirror.git
          git push personal main --force
